name: refresh_token_example
description: "Flutter example project that demonstrates how to refresh the auth token when token expires."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  chopper: ^8.0.1+1
  flutter:
    sdk: flutter
  http: ^1.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.11
  chopper_generator: ^8.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0


flutter:
  uses-material-design: true

